language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test

cache:
  directories:
    - $HOME/.m2

notifications:
  email: conork033@gmail.com,g00352227@gmit.ie